### ISSUE TITLE
katdal not finding TelescopeState receiver serial number sensor due to ignoring the band 

### ISSUE THREAD

**Issue by spassmoor** [ska-sa/katdal#114]
For example in the file produced on the AR1 correlator :
```
/var/kat/archive3/data/RTS/telescope_products/2018/01/18/1516315038.h5
```
The h5 file has the sensors :
```Python
In [13]: print h5.sensor['TelescopeState/m005_ap_indexer_position']
Out[13]: ['l' 'l' 'l' ..., 'l' 'l' 'l']
In [14]: print h5.sensor['TelescopeState/m005_rsc_rxl_serial_number']
Out[14]: [4029 4029 4029 ..., 4029 4029 4029]
```
But the code does not examine the band :
```Python
# Try sanitised version of RX serial number first
rx_sensor = 'TelescopeState/%s_rx_serial_number' % (ant,)
rx_serial = self.sensor[rx_sensor][0] if rx_sensor in self.sensor else 0
```

**Comment by ludwigschwardt** [comment]
Argh, what a mess - blame it on RTS :-P

The real digitiser sensor changed its name to `dig_l_band_noise_diode` and there was a PR ([katsdpingest #189](https://github.com/ska-sa/katsdpingest/pull/189)) to deal with this in August 2017. As part of this, I also took the liberty to rename `dig_l_band_noise_diode` to `dig_noise_diode` in cam2telstate since only one band will be active at a time anyway. This change suggested the same treatment for `rsc_rxl_serial_number` to `rx_serial_number`.

Bruce then convinced me not to rename sensors unnecessarily, and the rename was dropped from the PR before it was merged (to AR1's master) on 8 August 2017. Unfortunately the news never got to RTS, which received the sensor renaming version on 2 August 2017 already. In fact, it was used to test the code as it had to receive the changes before AR1.

So the end result is that RTS renames its noise diode and serial number sensors since the site update on 2017-11-15. Since PR #102 (approved by one Passmoor :-)) katdal supports the RTS version, with a fallback to the full sensor name in the old `TelescopeModel`, which inadvertently supported AR1 too. However, the recent site update on 2018-01-16 stripped those sensors out of `TelescopeModel`, leaving ARx in the lurch.

The solution would be to look for the sensor names in 3 places in v3, and 2 places in v4 (bye-bye RTS, good riddance!). I'll whip something up.
